 name: KillStreak
 version: 1.0
 main: me.biiing.killstreak.KillStreak
 commands:
   kills:
      description: Blank description.
      usage: /<command>
   deaths:
      description: Blank description.
      usage: /<command>