 name: KillStreak
 version: 1.2
 main: me.biiing.killstreak.KillStreak
 commands:
   kills:
      description: Displays how many players you have killed.
      usage: /<command>
   deaths:
      description: Displays how many times players have killed you.
      usage: /<command>
   streak:
      description: Displays your current killstreak.
      usage: /<command>
   highstreak:
      description: Displays your current highest streak
      usage: /<command>
   setkills:
      description: Edit a players kills.
      usage: /<command>
   setdeaths:
      description: Edit a players deaths.
      usage: /<command>
   setstreak:
      description: Edit a players streak.
      usage: /<command>
   sethighstreak:
      description: Edit a players highest streak.
      usage: /<command>


 permissions:
   killstreak.setkills:
      description: Use to set player kills.
      default: op
   killstreak.setdeaths:
      description: Use to set player deaths.
      default: op
   killstreak.setstreak:
      description: Use to set player streak.
      default: op
   killstreak.sethighstreak:
      description: Use to set players highest streak.
      default: op